# fly.toml app configuration file generated for andrew-kavas on 2025-10-21T22:53:23-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'andrew-kavas'
primary_region = 'dfw'

[build]
  build-target = 'production'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
